import numpy as np
import math

def calculate_list_psnr(original_scores, variant_scores, max_val=1.0):
    """
    Calculates the Peak Signal-to-Noise Ratio (PSNR) between two recommendation lists
    based on their item scores (e.g., NCF sigmoid scores).
    """
    original_scores = np.array(original_scores)
    variant_scores = np.array(variant_scores)
    
    # Check if lists are the same length
    if len(original_scores) != len(variant_scores):
        raise ValueError("Original and variant lists must have the same length for PSNR computation.")
        
    # Calculate Mean Squared Error (MSE) between the two ordered score vectors
    mse = np.mean((original_scores - variant_scores) ** 2)
    
    if mse == 0:
        return float('inf')  # The lists have identical scores (no noise)
        
    psnr = 10 * math.log10((max_val ** 2) / mse)
    return psnr

def calculate_dynamic_thresholds(psnr_values, lower_percentile=10, upper_percentile=90):
    """
    Dynamically calculates the lower and upper PSNR thresholds based on the 
    statistical distribution of the generated lists for a specific user.
    """
    # Filter out mathematically identical lists (infinite PSNR) so they don't break the statistics
    finite_psnrs = [p for p in psnr_values if not math.isinf(p)]
    
    if not finite_psnrs:
        return 0.0, float('inf')
        
    # Find the statistical boundaries based on percentiles
    lower_thresh = np.percentile(finite_psnrs, lower_percentile)
    upper_thresh = np.percentile(finite_psnrs, upper_percentile)
    
    return lower_thresh, upper_thresh

def filter_by_psnr_sweetspot(original_list, variant_lists, movie_scores_dict, 
                             lower_percentile=10, upper_percentile=90, max_val=1.0):
    """
    Dynamically filters variant lists for a user by calculating the mathematical sweet spot.
    
    Args:
        original_list (list): The original highly-accurate NCF top N movies for a user.
        variant_lists (list of lists): The multiple variant lists generated by weighted roulette.
        movie_scores_dict (dict): Mapping from movie ID to its predicted NCF score for this user.
                                  (e.g. { 'm1': 0.95, 'm2': 0.82 ... })
        lower_percentile (int): Lower statistical boundary of the distribution (default: 25th percentile).
        upper_percentile (int): Upper statistical boundary of the distribution (default: 75th percentile).
        max_val (float): Maximum possible NCF score value.
        
    Returns:
        tuple: (accepted_variants, calculated_lower_threshold, calculated_upper_threshold)
               accepted_variants is a list of dicts containing the list and its PSNR.
    """
    original_scores = [movie_scores_dict.get(m, 0.0) for m in original_list]
    
    # 1. Calculate PSNR for every generated variant
    variant_data = []
    psnr_values = []
    
    for variant in variant_lists:
        variant_scores = [movie_scores_dict.get(m, 0.0) for m in variant]
        psnr_val = calculate_list_psnr(original_scores, variant_scores, max_val=max_val)
        
        variant_data.append({
            'list': variant,
            'psnr': psnr_val
        })
        psnr_values.append(psnr_val)
        
    # 2. Mathematically determine the threshold bounds specific to this user's generated variants
    lower_thresh, upper_thresh = calculate_dynamic_thresholds(
        psnr_values, lower_percentile, upper_percentile
    )
    
    # 3. Filter using these dynamically calculated thresholds
    accepted_variants = []
    for data in variant_data:
        # Check if it falls in the calculated mathematical sweet spot!
        if lower_thresh <= data['psnr'] <= upper_thresh:
            accepted_variants.append(data)
            
    return accepted_variants, lower_thresh, upper_thresh

# Example Execution
if __name__ == "__main__":
    # Suppose NCF outputs this as the purely accurate Top 3 list for a user
    original_list = ['m1', 'm2', 'm3']
    
    # Suppose Weighted Roulette generated 10 variations
    variant_lists = [
        ['m1', 'm2', 'm3'], # Identical
        ['m1', 'm2', 'm4'], # Highly similar
        ['m1', 'm3', 'm2'], # Similar
        ['m1', 'm4', 'm5'], # Divergent
        ['m2', 'm4', 'm5'], # Divergent
        ['m3', 'm4', 'm6'], # Diverse
        ['m4', 'm5', 'm7'], # Diverse
        ['m5', 'm8', 'm9'], # Very Diverse
        ['m8', 'm9', 'm10'], # Completely Random Noise
        ['m9', 'm10', 'm8']  # Completely Random Noise
    ]
    
    # The predicted sigmoid scores from NCF
    movie_scores = {
        'm1': 0.98, 'm2': 0.95, 'm3': 0.91,
        'm4': 0.84, 'm5': 0.76, 'm6': 0.70, 'm7': 0.64,
        'm8': 0.24, 'm9': 0.18, 'm10': 0.10
    }
    
    print("--- Running Dynamic PSNR Sweet-Spot Filter ---")
    accepted, low, high = filter_by_psnr_sweetspot(
        original_list, 
        variant_lists, 
        movie_scores, 
        lower_percentile=10, 
        upper_percentile=90
    )
    
    print(f"Mathematically Calculated User Thresholds:")
    print(f"Lower Bound (10th Percentile): {low:.2f}")
    print(f"Upper Bound (90th Percentile): {high:.2f}")
    
    print(f"\nFound {len(accepted)} variant(s) inside this sweet spot!")
    for item in accepted:
        print(f"Accepted List: {item['list']} | PSNR: {item['psnr']:.2f}")
